"""Master Engine Adapter.

Provides sovereign execution gating and bulletproof error isolation between
Zephyr's market ingestion pipelines and the ZENIN Master Equation Orchestrator.
"""

from __future__ import annotations

import logging
from typing import Any, cast
import numpy as np

from iot_machine_learning.infrastructure.ml.engines.rosa_roja.algorithms.domain.execution import (
    ExecutionPlan,
)

logger = logging.getLogger(__name__)


class MasterEngineAdapter:
    """Sovereign adapter bridging Zephyr event stream to MasterEquationOrchestrator.

    Enforces total mathematical supremacy of ZENIN while ensuring that internal
    computational exceptions fail safely without stopping the execution runner.
    """

    def __init__(self, engine: Any, symbol: str = "SPY", config: Any | None = None) -> None:
        """Initializes the adapter with a quantitative engine instance.

        Args:
            engine: The MasterEquationOrchestrator instance.
            symbol: Ticker symbol managed by this engine instance.
            config: Optional runtime configuration for reference.
        """
        self._engine = engine
        self._symbol = symbol
        self._config = config

    @property
    def engine(self) -> Any:
        """Access the underlying master orchestrator."""
        return self._engine

    @property
    def symbol(self) -> str:
        """Ticker symbol associated with this adapter."""
        return self._symbol

    def evaluate(
        self,
        delta_state: np.ndarray,
        delta_time: float,
        current_position: float = 0.0,
    ) -> ExecutionPlan:
        """Evaluates a market state transition through the Master Equation pipeline.

        Applies Rule 4 (Zero Silent Errors): if any mathematical, numerical, or
        internal exception occurs, the error is logged and a failsafe ExecutionPlan
        is returned immediately to protect capital.

        Args:
            delta_state: State change vector ΔS (multidimensional NumPy array).
            delta_time: Time delta Δt between observations in seconds.
            current_position: Current open position size in the managed asset.

        Returns:
            ExecutionPlan: Authoritative plan generated by Master Equation or failsafe.
        """
        if self._engine is None:
            logger.error("MasterEngineAdapter [%s] has no active engine", self._symbol)
            return ExecutionPlan.HOLD(reason="NO_ACTIVE_ENGINE", alert=True)

        try:
            return cast(ExecutionPlan, self._engine.process_event(delta_state, delta_time))
        except Exception as exc:
            logger.critical(
                "ZENIN Master Equation crash on %s: %s",
                self._symbol,
                exc,
                exc_info=True,
            )
            safe_action = "EMERGENCY_FLUSH" if abs(current_position) > 1e-6 else "HOLD"
            return ExecutionPlan(
                action=safe_action,
                chosen_trajectory=None,
                global_confidence=0.0,
                envelope=None,
                invalidation_step=None,
                regime_alert=True,
                veto_details={"reason": f"FAILSAFE_ZENIN_CRASH: {exc}"},
            )

    def cancel_active_trajectory(self) -> None:
        """Cancels any tracked trajectory in the underlying trajectory engine."""
        if hasattr(self._engine, "cancel_active_trajectory"):
            try:
                self._engine.cancel_active_trajectory()
            except Exception as exc:
                logger.warning("Error cancelling active trajectory on %s: %s", self._symbol, exc)

    def reset(self) -> None:
        """Resets state in the underlying engine components."""
        if hasattr(self._engine, "reset"):
            try:
                self._engine.reset()
            except Exception as exc:
                logger.warning("Error resetting engine on %s: %s", self._symbol, exc)
