"""Market Replay (FASE 5) — reproducción del histórico sin look-ahead.

El paquete contiene el reloj, el contrato de feed, la ventana de
features, el predictor determinista de referencia y el engine
walk-forward. Todo es dominio puro (regla 3): consume entidades
``MarketObservation``; no conoce Alpaca/Binance/CSV/red.
"""

from .ablation import (
    ABLATION_EMA,
    ABLATION_FULL,
    ABLATION_MOMENTUM,
    ABLATION_NAIVE,
    ABLATION_NO_MEMORY,
    ABLATION_NO_MOE,
    ABLATION_NO_REGIME,
    ABLATIONS,
    AblationStats,
    AblationWindow,
    ablation_weights,
    ablation_window_stats,
    active_versions_by_window,
    aggregate_ablation,
    max_drawdown,
    parse_version_reason,
    portfolio_net_returns,
    render_ablation_matrix,
    sharpe_of,
)
from .baselines import (
    BASELINES,
    EmaCrossoverPredictor,
    MeanReversionPredictor,
    MomentumPredictor,
    NaivePredictor,
    PredictionSignal,
    Predictor,
    RandomPredictor,
)
from .benchmark import TrainedMomentumPredictor, TrainTestSplit, split_walk_forward
from .calibration import (
    BucketReport,
    BucketStatus,
    CalibrationReport,
    CalibrationThresholds,
    bucket_calibration,
    calibration_chart,
)
from .clock import Clock, ClockRollbackError, LiveClock, ReplayClock
from .engine import MarketReplayEngine, ReplayEngineConfig, ReplayRunResult
from .feature_window import FeatureWindow
from .feed import HistoricalFeed
from .metrics import MetricCollector, MetricKey, PredictionMetrics, confidence_bucket
from .predictor import predict_direction
from .regime import MarketRegime, classify_window
from .report import HorizonStat, PerformanceReport
from .significance import (
    BootstrapCi,
    ExpertMetricsCi,
    PermutationResult,
    PermWindow,
    RandomWinnerResult,
    WindowRecord,
    block_bootstrap,
    bootstrap_expert_metrics,
    difference_ci,
    permutation_test,
    pooled_sharpe,
    random_winner_test,
    recover_predicted_direction,
    weighted_acc,
    weighted_net,
    window_cumsum_maxdd,
)
from .walk_forward import (
    EdgeMetrics,
    HorizonEval,
    ModelMetrics,
    WfRow,
    WfWindow,
    evaluate_window,
    render_wf_report,
    weighted_model_metrics,
    wf_windows,
    window_regime,
)

__all__ = [
    "ABLATION_EMA",
    "ABLATION_FULL",
    "ABLATION_MOMENTUM",
    "ABLATION_NAIVE",
    "ABLATION_NO_MEMORY",
    "ABLATION_NO_MOE",
    "ABLATION_NO_REGIME",
    "ABLATIONS",
    "AblationStats",
    "AblationWindow",
    "ablation_weights",
    "ablation_window_stats",
    "active_versions_by_window",
    "aggregate_ablation",
    "max_drawdown",
    "parse_version_reason",
    "portfolio_net_returns",
    "render_ablation_matrix",
    "sharpe_of",
    "BASELINES",
    "EmaCrossoverPredictor",
    "MeanReversionPredictor",
    "MomentumPredictor",
    "NaivePredictor",
    "Predictor",
    "PredictionSignal",
    "RandomPredictor",
    "TrainedMomentumPredictor",
    "TrainTestSplit",
    "split_walk_forward",
    "Clock",
    "ClockRollbackError",
    "LiveClock",
    "ReplayClock",
    "BucketReport",
    "BucketStatus",
    "CalibrationReport",
    "CalibrationThresholds",
    "bucket_calibration",
    "calibration_chart",
    "MarketReplayEngine",
    "ReplayEngineConfig",
    "ReplayRunResult",
    "HorizonEval",
    "ModelMetrics",
    "EdgeMetrics",
    "WfRow",
    "WfWindow",
    "evaluate_window",
    "render_wf_report",
    "weighted_model_metrics",
    "wf_windows",
    "window_regime",
    "HistoricalFeed",
    "FeatureWindow",
    "MetricCollector",
    "MetricKey",
    "PredictionMetrics",
    "confidence_bucket",
    "predict_direction",
    "MarketRegime",
    "classify_window",
    "HorizonStat",
    "PerformanceReport",
    "BootstrapCi",
    "ExpertMetricsCi",
    "PermWindow",
    "PermutationResult",
    "RandomWinnerResult",
    "WindowRecord",
    "block_bootstrap",
    "bootstrap_expert_metrics",
    "difference_ci",
    "permutation_test",
    "pooled_sharpe",
    "random_winner_test",
    "recover_predicted_direction",
    "weighted_acc",
    "weighted_net",
    "window_cumsum_maxdd",
]
